# Generated by Django 6.0 on 2026-01-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_newspost_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-created_at']},
        ),
    ]
