# Generated by ChatGPT on 2026-02-01
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_newspost_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="Tiêu đề")),
                ("image", models.ImageField(upload_to="banners/", verbose_name="Ảnh banner")),
                ("link", models.URLField(blank=True, verbose_name="Liên kết")),
                ("is_active", models.BooleanField(default=True, verbose_name="Hiển thị")),
                ("display_order", models.PositiveIntegerField(default=0, verbose_name="Thứ tự hiển thị")),
                ("start_at", models.DateTimeField(blank=True, null=True, verbose_name="Bắt đầu")),
                ("end_at", models.DateTimeField(blank=True, null=True, verbose_name="Kết thúc")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
