# Generated by Django 5.2.6 on 2026-01-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_phone'),
        ('users', '0006_alter_userprofile_date_of_birth'),
    ]

    operations = [
    ]
