# Generated by Django 6.0 on 2026-01-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_options_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('momo', 'MoMo'), ('vietqr', 'VietQR')], max_length=20, verbose_name='Phương thức thanh toán'),
        ),
    ]
