# Generated by Django 6.0 on 2026-01-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('completed', 'Đã thanh toán'), ('failed', 'Thất bại'), ('canceled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
