# Generated by Django 4.2 on 2025-11-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('momo', 'MoMo'), ('bank_transfer', 'Chuyển khoản ngân hàng'), ('vnpay', 'VNPAY'), ('credit_card', 'Thẻ tín dụng')], max_length=20),
        ),
    ]
