# Generated by Django 6.0 on 2026-01-06 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_attribute_options_alter_category_options_and_more'),
        ('orders', '0001_initial'),
        ('users', '0002_alter_address_options_alter_userprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Mã giảm giá', 'verbose_name_plural': 'Quản lý mã giảm giá'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Danh sách đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Chi tiết đơn hàng', 'verbose_name_plural': 'Chi tiết đơn hàng'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Giảm phần trăm đơn hàng'), ('fixed', 'Giảm số tiền cố định'), ('ship_percent', 'Giảm phần trăm phí ship'), ('ship_fixed', 'Giảm tiền ship cố định')], default='percent', max_length=20, verbose_name='Loại giảm giá'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Giảm tối đa (0 là không giới hạn)', max_digits=10, verbose_name='Giảm tối đa'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(default=100, verbose_name='Số lần sử dụng tối đa'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_order_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giá trị đơn hàng tối thiểu'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Đã sử dụng'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Có hiệu lực từ'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(verbose_name='Có hiệu lực đến'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Giá trị giảm (VNĐ hoặc %)', max_digits=10, verbose_name='Giá trị'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.coupon', verbose_name='Mã giảm giá'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Số tiền giảm'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Mã đơn hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address', verbose_name='Địa chỉ giao hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=30000, max_digits=8, verbose_name='Phí giao hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('shipping', 'Đang giao'), ('delivered', 'Đã giao'), ('canceled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tổng tiền'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Đơn hàng'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lượng'),
        ),
    ]
