# Generated by Django 4.2 on 2025-12-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('momo', 'MoMo'), ('bank_transfer', 'Chuyển khoản ngân hàng'), ('vietqr', 'VietQR'), ('vnpay', 'VNPAY')], max_length=20),
        ),
    ]
