# Generated by Django 4.2 on 2025-12-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('momo', 'MoMo'), ('vietqr', 'VietQR'), ('payos', 'PayOS'), ('vnpay', 'VNPAY')], max_length=20),
        ),
    ]
