# Generated by Django 4.2 on 2025-12-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
