# Generated by Django 4.2 on 2025-12-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Giảm phần trăm đơn hàng'), ('fixed', 'Giảm số tiền cố định'), ('ship_percent', 'Giảm phần trăm phí ship'), ('ship_fixed', 'Giảm tiền ship cố định')], default='percent', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Giảm tối đa (0 là không giới hạn)', max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Giá trị giảm (VNĐ hoặc %)', max_digits=10),
        ),
    ]
