# Generated by Django 4.2 on 2025-11-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Danh sách sách'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Các thể loại'},
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_title_d3218d_idx',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_author_b941fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_price_9cc12f_idx',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_slug_ca552e_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='books_categ_slug_1c9755_idx',
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
