# Generated by Django 4.2 on 2025-11-18 05:12

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Ảnh sẽ lưu tại: media/books/covers/', null=True, upload_to=books.models.book_cover_upload_to),
        ),
    ]
