# Generated by Django 6.0 on 2026-01-21 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_detailed_description'),
        ('books', '0003_product_discount_percentage'),
    ]

    operations = [
    ]
