# Generated by Django 6.0 on 2026-01-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_merge_20260121_1459'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='product',
                    name='detailed_description',
                ),
            ],
        ),
    ]
