# Generated by ChatGPT on 2026-02-01
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_remove_product_detailed_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Kích hoạt"),
        ),
    ]
